export default {
  products: [
    {
      _id: "111111111111111111111111",
      name: "vegitable salad",
      category: "salad",
      image: "/image/product-1.jpg",
      price: 10,
      brand: "Fresh",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "2",
      name: "paneer tikka",
      category: "mains",
      image: "/image/product-2.jpg",
      price: 12,
      brand: "Fresh",
      rating: 4.5,
      numReviews: 10,
      countInStock: 45,
    },
    {
      _id: "3",
      name: "chicken lajawab",
      category: "mains",
      image: "/image/product-3.jpg",
      price: 10,
      brand: "Fresh",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "4",
      name: "chicken masuri",
      category: "mains",
      image: "/image/product-4.jpg",
      price: 10,
      brand: "Fresh",
      rating: 4.5,
      numReviews: 10,
      countInStock: 45,
    },
    {
      _id: "5",
      name: "chicken masala",
      category: "mains",
      image: "/image/product-5.jpg",
      price: 10,
      brand: "Fresh",
      rating: 4.5,
      numReviews: 10,
      countInStock: 45,
    },
    {
      _id: "6",
      name: "chicken curry",
      category: "mains",
      image: "/image/product-6.jpg",
      price: 10,
      brand: "Fresh",
      rating: 4.5,
      numReviews: 10,
      countInStock: 45,
    },
  ],
};

